title: susanna3003's homepage
description: GitHub Pages example for promoting a project
github_username: susanna3003
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
